title: "Finanzas I"
description: "Materiales del curso de Finanzas I — Luis Fernando Escobar Caba, UCB"
url: "https://lufesc.github.io"
baseurl: "/finanzas"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

markdown: kramdown
exclude:
  - README.md
